### ISSUE TITLE
bootstrap, seqconvert & treeCl bin load issues

### ISSUE THREAD

**Issue by smoretti** [kgori/treeCl#1]
Hi

I have issues loading bootstrap, seqconvert & treeCl found in bin/
Loading treeCl API looks to work fine (python -c "import treeCl")
(Python 2.7.5, Linux 2.6.32-573.8.1.el6.x86_64 treeCl 0.1.5)

$ bootstrap
Traceback (most recent call last):
  File "/software/Phylogeny/treeCl/0.1.5/bin/bootstrap", line 7, in <module>
    from treeCl.datastructs.trcl_seq import TrClSeq as Seq
ImportError: No module named datastructs.trcl_seq

$ seqconvert
Traceback (most recent call last):
  File "/software/Phylogeny/treeCl/0.1.5/bin/seqconvert", line 6, in <module>
    from treeCl.datastructs.seq import Seq
ImportError: No module named datastructs.seq

$ treeCl
Traceback (most recent call last):
  File "/software/Phylogeny/treeCl/0.1.5/bin/treeCl", line 17, in <module>
    from treeCl import Collection, Clustering, DistanceMatrix, Partition, Plotter, Scorer
ImportError: cannot import name Clustering

Other tools in bin/ look to load fine.

Don't know what to do to solve that.
Regards

**Comment by kgori** [comment]
Thanks for letting me know about this. The problem is that the scripts in bin haven't been updated in a while, and they try to import modules under outdated names. I'll update them.

**Comment by smoretti** [comment]
OK, thanks, waiting for the update.

Also **python setup.py test** returns an error about UniCode:
_skip test because of Non-ASCII character '\xe2' in file treeCl/collection.py_
Don't know if this is linked with my terminal settings or with an error.

Regards

**Comment by kgori** [comment]
The update is in place. I've removed the non ascii character (which was something invisible that I'd cut&pasted from somewhere), and updated the scripts. I'll leave the issue open until you can install successfully.

**Comment by smoretti** [comment]
Hi
Installation is successful now, thanks.

Just two remarks:
- no more **treeCl script** in bin/. I guess this script is what most users not familiar with Python want to use.
- **python setup.py test**  returns a single error for me (_ERROR: test_random (tests.test.PartitionTests)_) Do you also see that on your side?

**Comment by kgori** [comment]
Hi. Glad you have it installed. Thanks for the report about the failing test, it was badly written.
