### ISSUE TITLE
No match found for "Final GAMMA  likelihood

### ISSUE THREAD

**Issue by fanliang123** [kgori/treeCl#11]
Hi kgoryi,

I do not know what is wrong with the follow code, could you help me?

In [1]: import treeCl

In [2]: c = treeCl.Collection(input_dir='align_result_fasta', file_format='fasta')
Loading files: 1984 of 1984 |##############################################| Elapsed Time: 0:00:55 Time: 0:00:55

In [3]: c.calc_trees(executable='raxmlHPC-PTHREADS-AVX',
   ...:              threads=30,
   ...:              model='PROTGAMMAWAGX',
   ...:              fast_tree=True)
---------------------------------------------------------------------------| Elapsed Time: 0:11:21 ETA:  1:05:06
ParseException                            Traceback (most recent call last)
<ipython-input-3-f11b8d8f972b> in <module>()
      2              threads=30,
      3              model='PROTGAMMAWAGX',
----> 4              fast_tree=True)

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/collection.pyc in calc_trees(self, indices, task_interface, jobhandler, batchsize, **kwargs)
    407         # Dispatch work
    408         msg = '{} Tree estimation'.format(task_interface.name)
--> 409         map_result = jobhandler(task_interface.get_task(), args, msg, batchsize)
    410 
    411         # Process results

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/parutils.pyc in __call__(self, task, args, message, batchsize)
    210         if batchsize > 1:
    211             logger.warn("Setting batchsize > 1 has no effect when using a SequentialJobHandler")
--> 212         return sequential_map(task, args, message)
    213 
    214 

...
...
...

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/parutils.pyc in sequential_map(task, args, message)
    113     map_result = []
    114     for (i, arglist) in enumerate(tupleise(args), start=1):
--> 115         map_result.append(task(*arglist))
    116         pbar.update(i)
    117     pbar.finish()

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/tasks.pyc in raxml_task(executable, alignment_file, model, partitions_file, outfile, threads, parsimony, fast_tree)
    280 
    281         parser = RaxmlParser()
--> 282         result = parser.to_dict(info_file, result_file, dash_f_e=dash_f_e)
    283 
    284         if outfile is not None:

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/parsers.pyc in to_dict(self, info_filename, tree_filename, dash_f_e)
    209         """
    210         if dash_f_e:
--> 211             return self._dash_f_e_to_dict(info_filename, tree_filename)
    212         else:
    213             return self._to_dict(info_filename, tree_filename)

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/treeCl/parsers.pyc in _dash_f_e_to_dict(self, info_filename, tree_filename)
    183         """
    184         with open(info_filename) as fl:
--> 185             models, likelihood, partition_params = self._dash_f_e_parser.parseFile(fl).asList()
    186 
    187         with open(tree_filename) as fl:

/home/blzhang/.pyenv/versions/2.7.11/lib/python2.7/site-packages/pyparsing.pyc in parseFile(self, file_or_filename, parseAll)
   2148             else:
   2149                 # catch and re-raise exception from here, clears out pyparsing internal stack trace
-> 2150                 raise exc
   2151 
   2152     def __eq__(self,other):

ParseException: No match found for "Final GAMMA  likelihood:" (at char 2629), (line:101, col:1)

**Comment by alexweisberg** [comment]
I am getting the same error message, it is particularly happening when I try to run multiple runs at the same time (ie multiple SGE jobs to calculate bootstrap trees).

**Comment by alexweisberg** [comment]
I realized what my problem was, some of the compute nodes on our cluster did not have support for AVX. When I switched to SSE3 (raxmlHPC-PTHREADS-SSE3) everything worked correctly.

**Comment by kgori** [comment]
@fanliang123 @alexweisberg Thanks for reporting (and solving) this issue. In this case the error message was not very helpful, was it? I'll try to improve this.
