### ISSUE TITLE
scaling inter-tree distance calculations to 3000+ gene trees

### ISSUE THREAD

**Issue by rohanmaddamsetti** [kgori/treeCl#17]
Hi,

First, thanks for writing this cool piece of software. I'm running treeCl on a jupyter notebook with 200GB of memory (running on a cluster). I want to calculate euclidean distance between 3289 gene trees, each with <200 leaves. For this use case, my jupyter notebook crashes because it exceeds 200GB of memory.

I'm going to try to write a workaround for myself (probably writing distances to disk rather than storing in memory). But I wanted to report this memory issue-- any advice for how to work around would be appreciated as well :)

**Comment by kgori** [comment]
Hi,
Thanks for this report. I would have thought that 200Gb would be more than enough memory for your problem. I guess I should break out Valgrind and look for memory leaks.

**Comment by rohanmaddamsetti** [comment]
Thanks for taking a look, Kevin. My code closely follows the example. My trees are attached and I will send you the corresponding alignments in a separate email. I hope this helps for replicating this bug.

import treeCl
aln_dir = 'reduced_a2m_alignments'
tree_dir = 'bork-reduced-gene-trees'
c = treeCl.Collection(input_dir=aln_dir, trees_dir=tree_dir, file_format='fasta')

dm = c.get_inter_tree_distances('euc') ## memory problem here
[bork-reduced-gene-trees.zip](https://github.com/kgori/treeCl/files/2160585/bork-reduced-gene-trees.zip)

**Comment by rohanmaddamsetti** [comment]
Hi Kevin, here are my alignments as a Google Drive link. Hope it helps and
thanks again for looking into this. Cheers, Rohan
​
 reduced_a2m_alignments.zip
<https://drive.google.com/file/d/123hA5uCefpxVoLkr6W6WYwX66fxwU9C8/view?usp=drive_web>
​

**Comment by kgori** [comment]
Hi,
I think I've got this. The short story is that ```get_inter_tree_distances``` prepares a list of all the pairs of trees, and then computes the distance for each pair. The memory issue comes from that list being HUGE when you have as many trees as you do. If I switch the list for a generator expression then it doesn't have to store everything in memory ahead of time. For your example this fits into ~2Gb on my laptop.

It's going to take a while to make the switch to generators everywhere and make sure all my tests still pass, so this won't be in a release for a while, but there's an early, (hopefully) working fix in commit ```1c4b5e1920``` on branch ```issue_17_memory```. Caveat utilitor, and all that...

Kevin

**Comment by rohanmaddamsetti** [comment]
Thanks Kevin! I updated my treeCl installation, and now my code is running fine. I'll go ahead and close this issue.

**Comment by kgori** [comment]
Glad it worked. I'm reopening this until it's worked into a release.

**Comment by kgori** [comment]
Fixed in release 0.1.37
