### ISSUE TITLE
Simple Questions

### ISSUE THREAD

**Issue by fbemm** [kgori/treeCl#18]
Hey,

I got to relatively simple questions:

1) Is it possible to subset a tree collection somehow? Basically something like: treeCl.collection.subset(list())

2) What would be the easiest way to shuffle leave names for an individual tree or all trees in a collection individually?

Thx,
F

**Comment by kgori** [comment]
Hi,

1. Collections are subsettable, so you can build a new collection like this:

```
    subset = old_collection[2:5] + old_collection[7:9]
    new_collection = Collection(records=subset)
```


2. Trees have a randomise_labels method, so like this:

```
    for record in collection:
        tree_obj = treeCl.Tree(record.tree)
        shuffled = tree_obj.randomise_labels()
        record.parameters.ml_tree = shuffled.newick
```
