### ISSUE TITLE
Collection is undefined

### ISSUE THREAD

**Issue by williamhuntpalmer** [kgori/treeCl#2]
Hi,

I installed treeCl and everything seems to go fine. For some reason Biopython's clustering doesn't seem to be available but wasn't planning on using k medoids clustering anyways!

```
-bash-4.1$ python
Python 2.7.8 (default, Dec  5 2014, 12:37:39) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import treeCl
Biopython unavailable - kmedoids clustering disabled
>>>

```

However, when I attempt to load my data with the code provided, I get the following error: 

```

>>> c = Collection(input_dir='/path/to/my/alignments', file_format='fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Collection' is not defined
>>> 

```

Any idea what is going on?

Cheers,
Billy

**Comment by kgori** [comment]
Hi Billy,

Have you imported Collection? You can do
from treeCl import Collection
c = Collection(...)

or you can do
import treeCl
c = treeCl.Collection(...)

Either way, you need to have Collection in scope to be able to use it.

Hope this helps,
Kevin.

**Comment by williamhuntpalmer** [comment]
Well, I feel silly - that was all! For some reason I was under the impression that "import x" would import everything (and more) that the "from x import y" would import. Thanks for the quick reply!
