### ISSUE TITLE
File handling in `calc_trees`

### ISSUE THREAD

**Issue by szitenberg** [kgori/treeCl#3]
Thanks for an extremely useful package!  
When reading more then ~900 alignments or when running consecutively on different alignment sets, I get a `to many open files` error. My current workaround is to restart the kernel between iterations (jupyter notebook).  

Amir

This is my code:  

<pre>
c = treeCl.Collection(input_dir=path, file_format='fasta')

c.calc_trees(executable='raxmlHPC-PTHREADS',
             threads=14,  
             model='GTRGAMMA', 
             fast_tree=False)  
</pre>

The traceback is:  

<pre>
IOError                                   Traceback (most recent call last)
<ipython-input-117-53526b906097> in <module>()
      7              threads=14,  # use multithreaded raxml
      8              model='GTRGAMMA',  # this model of evolution
----> 9              fast_tree=False)  # 

/home/amir/anaconda2/lib/python2.7/site-packages/treeCl/collection.pyc in calc_trees(self, indices, task_interface, jobhandler, batchsize, **kwargs)
    362 
    363         # Scrape args from records
--> 364         args, to_delete = task_interface.scrape_args(records, **kwargs)
    365 
    366         # Dispatch work

/home/amir/anaconda2/lib/python2.7/site-packages/treeCl/tasks.pyc in scrape_args(self, records, executable, partition_files, model, outfiles, threads, parsimony, fast_tree)

/home/amir/anaconda2/lib/python2.7/site-packages/treeCl/alignment.pyc in get_alignment_file(self, as_phylip)

/home/amir/anaconda2/lib/python2.7/site-packages/treeCl/alignment.pyc in write_alignment(self, filename, file_format, interleaved)

/home/amir/anaconda2/lib/python2.7/site-packages/Bio/AlignIO/__init__.pyc in write(alignments, handle, format)

/home/amir/anaconda2/lib/python2.7/contextlib.pyc in __enter__(self)

/home/amir/anaconda2/lib/python2.7/site-packages/Bio/File.pyc in as_handle(handleish, mode, **kwargs)

IOError: [Errno 24] Too many open files: '/tmp/tmpWsw6ye'
</pre>

**Comment by kgori** [comment]
Hi, thanks for the info. I've had this bug before but I thought I'd fixed
it. I guess not! When making temp files it opens the file object and a
spawns a file descriptor in the OS. 'Too many open files' means the file
descriptor is not being closed properly. Do you know what version of treeCl
you have?

**Comment by szitenberg** [comment]
Yes. It's pip installed, version 0.1.13

**Comment by kgori** [comment]
This should be fixed with version 0.1.16 / commit 93b2d614

**Comment by szitenberg** [comment]
Thanks
