### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by davidemms** [kgori/treeCl#4]
Hi 

I'm trying to install treeCl on a computer with gcc version 4.7.3 and I get the following error message:

creating build/temp.linux-x86_64-2.7/extensions/tree_collection/src

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iextensions/tree_collection/src/eigen3 -I/usr/include/python2.7 -c extensions/tree_collection/cython/py_wrapper.cpp -o build/temp.linux-x86_64-2.7/extensions/tree_collection/cython/py_wrapper.o -std=c++1y

gcc: error: unrecognized command line option ‘-std=c++1y’

error: command 'gcc' failed with exit status 1

I can post the full output if that is helpful.  From what I can see gcc 4.7.3 doesn't support this standard.

All the best
David

**Comment by kgori** [comment]
Thanks for this David. This should be fixable by requiring -std=c++11 in place of c++1y. I don't think I am  using C++14 features (i.e. std::make_unique) any more, so it should just work. I'll test this out this afternoon.

**Comment by kgori** [comment]
The new version 0.1.17 should be compatible with gcc 4.7

**Comment by davidemms** [comment]
Thanks! I'm still having a problem building unfortunately, I've attached the output from running the setup script.
[BuildLog.txt](https://github.com/kgori/treeCl/files/236585/BuildLog.txt)

**Comment by kgori** [comment]
What version of cython are you running?

**Comment by davidemms** [comment]
Version 0.15.1

**Comment by kgori** [comment]
That version is too old for the C++ -> python string conversion code to work. Upgrade to at least version 19 and you should be OK.

**Comment by davidemms** [comment]
Thanks, I've got it installed now. I've still got a problem which might be separate from the installation so I'll create a new ticket.
