### ISSUE TITLE
scikit-bio no longer works with python 2

### ISSUE THREAD

**Issue by vcorby** [kgori/treeCl#7]
FYI: Looks like they [made a change to sci-kit bio](http://scikit-bio.org/). It doesn't work with Python 2 anymore...

**Comment by RoyChaudhuri** [comment]
If anyone runs into this issue, a workaround is to run "pip install scikit-bio==0.4.2" before "pip install treeCl"

**Comment by kgori** [comment]
Scikit bio is pinned to version 0.4.2 in the treeCl setup.py.
